crate/cratedb-toolkit

- .github/CODEOWNERS
- .github/workflows/main.yml
- .gitignore
- CHANGES.rst
- cratedb_retentions/cli.py
- dags/data_retention_delete_dag.py
- dags/data_retention_reallocate_dag.py
- dags/data_retention_snapshot_dag.py
- pyproject.toml
- tests/test_dummy.py
- Add project metadata file `pyproject.toml`.
- CI/GHA configuration, without anything behind.
- Code formatting.
> Chore: Project boilerplate for standalone application

- .github/workflows/main.yml
- .github/workflows/oci.yml
- MANIFEST.in
> CI: A few fixes to get out nightly OCI builds

- README.md
- cratedb_retention/cli.py
- cratedb_retention/core.py
- cratedb_retention/model.py
- cratedb_retention/setup/schema.py
- pyproject.toml
- tests/conftest.py
Bring in support for connecting to, and running data retention jobs, on [CrateDB Cloud](https://console.cratedb.cloud/).
> Expand usability: Use with CrateDB Cloud

- README.md
Document how to run a demonstration setup on Podman or Docker.
> Expand usability: Use with Podman or Docker

- README.md
- cratedb_retention/setup/schema.sql
- doc/backlog.md
- pyproject.toml
- tests/conftest.py
- README: Add a header section linking to relevant resources
- Naming things: Use "toolkit" instead of "manager"
- Document the layout and fields of the retention policy entity. Needs help! /cc @hammerhead 🙏 
- Update backlog
> Documentation improvements

- README.md
- cratedb_retention/cli.py
- cratedb_retention/util/cli.py
- cratedb_retention/util/common.py
- pyproject.toml
- tests/test_cli.py
- Only log SQL statements when using `--verbose`
- Improve log format
> Improve logging

- cratedb_retention/cli.py
- cratedb_retention/store.py
- tests/test_store.py
For enumerating all assigned tags.
> Add `list-tags` subcommand

- CHANGES.md
- README.md
- cratedb_toolkit/cli.py
- doc/sandbox.md
- examples/retention_edit.py
- examples/retention_retire_cutoff.py
- pyproject.toml
- release/oci/selftest.sh
> Rename package to `cratedb-toolkit`

- CHANGES.md
- cratedb_toolkit/cli.py
- cratedb_toolkit/cluster/cli.py
- cratedb_toolkit/cluster/croud.py
- cratedb_toolkit/cluster/util.py
- cratedb_toolkit/io/README.md
- cratedb_toolkit/io/cli.py
- cratedb_toolkit/io/croud.py
- cratedb_toolkit/job/cli.py
- cratedb_toolkit/job/croud.py
- cratedb_toolkit/model.py
- cratedb_toolkit/shell/cli.py
- cratedb_toolkit/util/cli.py
- cratedb_toolkit/util/common.py
- cratedb_toolkit/util/crash.py
- cratedb_toolkit/util/croud.py
- cratedb_toolkit/util/data.py
- doc/backlog.md
- doc/bugs.md
- pyproject.toml
- tests/io/test_import.py
Wraps a few calls of `croud` into a different kind of API, mostly about importing data.
Check your clusters.
```shell
croud me
```
Define the cluster id of the CrateDB Cloud Cluster you want to connect to, and its connection credentials.
```shell
export CRATEDB_CLOUD_CLUSTER_ID='e1e38d92-a650-48f1-8a70-8133f2d5c400'
export CRATEDB_USERNAME='admin'
export CRATEDB_PASSWORD='3$MJ5fALP8bNOYCYBMLOrzd&'
```
Load data.
```shell
ctk load table https://github.com/crate/cratedb-datasets/raw/main/cloud-tutorials/data_weather.csv.gz
```
Inquire data.
```shell
ctk shell --command="SELECT * FROM data_weather LIMIT 10;"
```
There are two more commands.
```shell
ctk cluster info
ctk list-jobs
```
> SDK and CLI for CrateDB Cloud Data Import APIs

- CHANGES.md
- cratedb_toolkit/datasets/model.py
- cratedb_toolkit/util/database.py
- pyproject.toml
> datasets: Fix compatibility with Python 3.7

- pyproject.toml
> Chore: Update to mypy 1.10 and ruff 0.4

- pyproject.toml
> Dependencies: Use `sqlalchemy-cratedb>=0.36.1,<1`

- .github/workflows/mongodb.yml
- doc/adapter/rockset.md
- pyproject.toml
That Dependabot PR does not converge well.
- GH-179
> Chore: A few maintenance adjustments

- README.md
- doc/adapter/pymongo.md
- doc/adapter/rockset.md
- doc/cfr/index.md
- doc/index.md
- doc/install.md
- doc/io/index.md
- doc/release.md
- doc/retention.md
- doc/sandbox.md
- doc/wtf/backlog.md
- doc/wtf/index.md
- examples/rockset/java/pom.xml
- examples/rockset/javascript/package.json
- pyproject.toml
> Project: Move from GitHub organization `crate-workbench` to `crate`

- pyproject.toml
> Chore: Unpin `kaggle` dependency

- .github/workflows/influxdb.yml
- .github/workflows/main.yml
- .github/workflows/mongodb.yml
- CHANGES.md
- cratedb_toolkit/io/processor/kinesis_lambda.py
- pyproject.toml
> Dependencies: Update to commons-codec 0.0.7

- cratedb_toolkit/io/mongodb/extract.py
- tests/io/mongodb/test_extract.py
No semantic changes, just some improvements to the code base.
- Add utility functions `get_types` and `trim_schema` for streamlined "type extractor" unit tests
- Do not use `t` as variable, because it's used as an alias for `typing`
> MongoDB: Improve software tests. Naming things.

- CHANGES.md
- cratedb_toolkit/io/mongodb/adapter.py
- cratedb_toolkit/io/processor/kinesis_lambda.py
- pyproject.toml
Update needed to be compatible with pymongo >=4.9.
> MongoDB: Update to pymongo 4.9

- tests/io/dynamodb/test_copy.py
The software test included here verifies that the URL query parameter `batch-size` is correctly propagated to the relevant incantation at boto3's DynamoDB client.
- GH-299
> DynamoDB: Verify `batch-size` URL parameter

- cratedb_toolkit/testing/testcontainers/cratedb.py
- cratedb_toolkit/util/database.py
> SQLAlchemy: Add spots where to enable query logging

- cratedb_toolkit/api/main.py
Updated `main.py` to fix the dataset URL to the new location.
> Update main.py to fix dataset URL

- cratedb_toolkit/retention/core.py
- pyproject.toml
- tests/io/dynamodb/test_copy.py
- tests/io/mongodb/test_copy.py
- tests/retention/conftest.py
- [Chore: Satisfy Ruff linter](https://github.com/crate/cratedb-toolkit/commit/1d597811d19a25b4da7d820f8527f8967b6f65d1)
- [CrateDB: Dynamic nested arrays ARE supported now](https://github.com/crate/cratedb-toolkit/pull/359/commits/cd4a63e3150715d72d0f79fec42ce9f6c6123993)
- Bundle Dependabot updates.
- GH-356
- GH-357
- GH-358
> Chore: Maintenance 2025W05

- cratedb_toolkit/datasets/tutorial.py
- doc/datasets.md
By providing a little API that wraps SQL loader snippets of [cratedb-datasets](https://github.com/crate/cratedb-datasets), it becomes easier to load the wind farms dataset programmatically.
- https://github.com/crate/cratedb-datasets/pull/26
/cc @simonprickett
> Datasets: Register UK wind farm dataset

- pyproject.toml
> Chore: Update to "verlib2<0.3"

- pyproject.toml
> Chore: Relax dependency on poethepoet and pyproject-fmt

- cratedb_toolkit/cli.py
- cratedb_toolkit/docs/cli.py
- cratedb_toolkit/docs/settings.py
- doc/docs-api.md
- doc/index.md
- pyproject.toml
- tests/docs/test_cli.py
Integrate GH-398.
- Format code and satisfy linters
- Provide CLI entrypoint
- Add software tests
> Docs API: Integrate into CLI. Add documentation.

- CHANGES.md
- pyproject.toml
> CLI: Downgrade to Click 8.1, as the code is not compatible with 8.2 yet

- .github/workflows/dynamodb.yml
- .github/workflows/influxdb.yml
- .github/workflows/mongodb.yml
- pyproject.toml
- tests/io/dynamodb/conftest.py
Probe improving dependency definitions for [Testcontainers Python](https://pypi.org/project/testcontainers/).
- GH-461
> Testing: Improve package dependencies for `testcontainers` ensemble

- .github/workflows/dynamodb.yml
- .github/workflows/influxdb.yml
- .github/workflows/main.yml
- .github/workflows/mongodb.yml
- .github/workflows/release-app.yml
- .github/workflows/release-oci.yml
- .github/workflows/release-pypi.yml
- pyproject.toml
What the title says.
- https://github.com/daq-tools/lorrystream/pull/182
> CI: Use the `uv` package manager. It is fast.

- .dlt/config.toml
- .github/workflows/postgresql.yml
- CHANGES.md
- cratedb_toolkit/cluster/core.py
- cratedb_toolkit/io/core.py
- cratedb_toolkit/io/ingestr/api.py
- cratedb_toolkit/io/ingestr/boot.py
- cratedb_toolkit/model.py
- cratedb_toolkit/testing/testcontainers/cratedb.py
- doc/io/index.md
- doc/io/postgresql/index.md
- doc/io/postgresql/research.md
- pyproject.toml
- tests/adapter/test_pymongo.py
- tests/io/ingestr/test_postgresql.py
We found the need to migrate data from PostgreSQL to CrateDB fluently.
- Full-load: Uses adapter nozzle based on [ingestr](https://github.com/bruin-data/ingestr) / [dlt](https://github.com/dlt-hub/dlt).
- CDC: Patch includes research docs. Implementation was started using best-of-breed pipeline elements.
- Installation:
```shell
uv tool install --upgrade 'cratedb-toolkit[io-ingestr] @ git+https://github.com/crate/cratedb-toolkit@postgresql-cdc'
```
- Documentation: https://cratedb-toolkit--445.org.readthedocs.build/io/postgresql/
Invoke `full-load` operation.
```shell
ctk load table \
"postgresql://pguser:secret11@postgresql.example.org:5432/postgres?table=information_schema.tables" \
--cluster-url="crate://crate:na@localhost:4200/testdrive/postgresql_tables"
```
- …
> I/O: Adapter for PostgreSQL

- cratedb_toolkit/io/ingestr/api.py
- doc/io/dms/standalone.md
- doc/io/index.md
- doc/io/ingestr/index.md
- doc/io/postgresql/index.md
A few documentation improvements about loading data with ingestr.
https://cratedb-toolkit--476.org.readthedocs.build/io/ingestr/
- GH-463
> I/O: Improve documentation page about ingestr

- cratedb_toolkit/io/ingestr/api.py
> Chore: Fix boot-time warning about ingestr

- README.md
- doc/adapter/pymongo.md
- doc/adapter/rockset.md
- pyproject.toml
> Status: Make it beta
