crate/cratedb-toolkit

README.md, cratedb_retention/cli.py, cratedb_retention/model.py, cratedb_retention/setup/schema.py, cratedb_retention/setup/schema.sql, tests/conftest.py
It is advised to use singular table names for entities these days.
> For new projects or where you can easily change the name of entities
> then I would say you must use singular names, for older projects
> you'll need to be a bit more pragmatic!
>
> --The.AgileSQL.Club
>
> -- https://www.dbdebunk.com/2019/05/naming-relations-singular-or-plural.html
> The arguments for plural are straightforward: It reads well in the `FROM` clause.
> The arguments for singular are more subtle: It reads well everywhere else in the SQL query.
>
> -- https://www.teamten.com/lawrence/programming/use-singular-nouns-for-database-table-names.html
> **How to name tables?**
> - Use lower letters when naming database objects. For separating words in the database object name, use underscore.
> - Use singular for …
=> Naming things: Use `retention_policy` (singular) as table name

cratedb_retention/model.py, cratedb_retention/setup/schema.py, cratedb_retention/strategy/delete.py, cratedb_retention/strategy/delete_tasks.sql, cratedb_retention/strategy/policy.sql, cratedb_retention/strategy/reallocate.py, cratedb_retention/strategy/reallocate_tasks.sql, cratedb_retention/strategy/snapshot.py, cratedb_retention/strategy/snapshot_tasks.sql
The SQL templates for the different data retention strategies all use the same SQL DQL clause for accessing columns of the retention policy table. Their corresponding Python support code deviates only slightly in the number and order of the decoded columns.
This patch generalizes that, by adding a dedicated and generic `RetentionPolicy` object, where corresponding database records are unmarshalled to. It tremendously improves maintenance, trimming down the amount of code needed to implement specific strategies significantly, saving a few lines of boilerplate for each.
=> Add `RetentionPolicy` entity, and generalize SQL templates

README.md, cratedb_retention/cli.py, cratedb_retention/core.py, cratedb_retention/model.py, cratedb_retention/setup/schema.py, examples/basic.py, pyproject.toml, tests/conftest.py, tests/test_examples.py
This patch brings in documentation how to use the toolkit as a library. Along the lines, it takes the chance to adjust the naming of a few components a bit: `Engine` -> `RetentionJob`, `Settings` -> `JobSettings`.
=> Expand usability: Use as a library, and naming things

cratedb_retention/model.py, cratedb_retention/strategy/policy.sql
For the sake of completeness, also return the value of the `retention_period` column, when loading retention policy records from the corresponding database table.
=> SQL schema: Also return original value of `retention_period`

README.md, cratedb_retention/setup/schema.sql, examples/basic.py
By moving the `strategy` column to the front of the retention policy table, a retention policy record almost reads like natural language.
```sql
-- A policy using the REALLOCATE strategy.
INSERT INTO "ext"."retention_policy"
(strategy, table_schema, table_name, partition_column, retention_period, reallocation_attribute_name, reallocation_attribute_value)
VALUES
('reallocate', 'doc', 'raw_metrics', 'ts_day', 60, 'storage', 'cold');
```
@hammerhead: Would that statement be correct, to describe this retention policy in human language? Can you correct it, if I got it wrong?
> **Reallocate** data from the `"doc"."raw_metrics"` table to machines running nodes tagged with `node.attr.storage=cold`, on partitions defined by column `ts_day`, when it is older than **60** days.
See also …
=> SQL schema: Move `strategy` column to front of retention policy table

README.md, cratedb_retention/cli.py, cratedb_retention/core.py, cratedb_retention/model.py, cratedb_retention/setup/schema.sql, cratedb_retention/store.py, cratedb_retention/strategy/delete.py, cratedb_retention/strategy/policy.sql, cratedb_retention/strategy/reallocate.py, cratedb_retention/strategy/snapshot.py, cratedb_retention/util/cli.py, cratedb_retention/util/database.py, examples/basic.py, examples/edit.py, pyproject.toml, tests/conftest.py, tests/test_cli.py, tests/test_database.py, tests/test_examples.py, tests/test_store.py
It became clear the program needed a better data model, and CLI interfaces, than only running SQL statements manually for inserting and editing retention policy rules.
- Data model API using SQLAlchemy
- CLI API using Click
=> More APIs and SQLAlchemy, less SQL

tests/conftest.py, tests/test_cli.py
Now using the [`generate_series()`](https://crate.io/docs/crate/reference/en/5.3/general/builtins/table-functions.html#table-functions-generate-series) function to populate example data into the `raw_metrics` and `sensor_readings` tables.
=> Use `generate_series` to populate example data

README.md, cratedb_retention/cli.py, tests/test_cli.py
Instead of obtaining the database URI from the command-line, the user can now use the `CRATEDB_URI` environment variable.
=> Accept `CRATEDB_URI` environment variable

README.md, cratedb_retention/cli.py, cratedb_retention/setup/schema.sql, cratedb_retention/strategy/reallocate.py, tests/conftest.py
The storage zones for the "REALLOCATE" strategy have been called `hot` vs. `cold`. @seut suggested to use the labels `hot` vs. `warm` instead. It makes sense to me to discriminate storage zones this way, because reallocated data is still available for querying (warm), while deleted or outphased/snapshotted data isn't (cold). Thanks.
=> Naming things: Use "hot" vs. "warm" labels for the "REALLOCATE" strategy

cratedb_retention/cli.py, cratedb_retention/store.py, examples/edit.py, tests/conftest.py, tests/test_cli.py, tests/test_store.py
=> Add synthetic UNIQUE constraint to retention policy table

README.md, cratedb_retention/cli.py, cratedb_retention/core.py, cratedb_retention/model.py, cratedb_retention/setup/schema.py, tests/conftest.py, tests/test_cli.py
- By using the `--dry-run` command-line option, the program will only pretent to invoke data retention SQL statements.
- Instead, it will send them to the logger for inspection and education purposes.
- Currently, this works on `setup` and `run` subcommands.
=> Add "dry run" mode, to pretend invoking SQL statements

examples/edit.py, examples/full.py
At the same time, better use modernized components, and get rid of procedural helper functions.
=> Examples: Make sure they work out of the box, even with vanilla CrateDB settings

.github/workflows/main.yml, doc/backlog.md, pyproject.toml, tests/conftest.py, tests/test_cli.py
- Tests: Stronger linting.
- Tests: Stronger assertions about number of records in database.
- CI: Use `TC_KEEPALIVE` to not tear down Testcontainers.
I've always used it in my sandbox, but missed to bring it to CI.
It significantly reduces overall runtime, because the CrateDB container takes a few seconds to boot each time.
- Update backlog.
=> Chore: This and that

README.md, cratedb_retention/util/database.py, pyproject.toml, tests/conftest.py, tests/test_cli.py, tests/testcontainers/azurite.py, tests/testcontainers/cratedb.py, tests/testcontainers/minio.py, tests/testcontainers/util.py
The "SNAPSHOT" strategy has not been tested thoroughly yet.
```diff
- # FIXME: This currently can not be tested, because it needs a snapshot repository.
- # TODO: Provide an embedded MinIO S3 instance to the test suite.
```
This patch provides additional infrastructure to the test suite, and validates the full roundtrip by creating a snapshot repository, running the snapshot procedure, and verifying that data has moved correctly.
For verifying different repository types, different helper services and APIs are used.
- Filesystem: Uses the [Python Docker API](https://pypi.org/project/docker/) to introspect the filesystem of the OCI container where CrateDB is running.
- AWS S3: Uses [MinIO](https://github.com/minio/minio) to provide a compatible service.
- Azure Blob Storage: Uses …
=> Tests: Add integration tests for the "SNAPSHOT" strategy

README.md, cratedb_retention/cli.py, cratedb_retention/core.py, examples/retire_cutoff.py, tests/test_core.py, tests/test_examples.py
I am extremely wary about using default parameters for the engine parts of such a powerful application, but in this particular case, I think it is fine to assume `today()` as default parameter for the `cutoff_day` parameter obtained from the caller.
=> Core: When running jobs without cutoff date, use `today()` as default

CHANGES.md, cratedb_retention/util/data.py, cratedb_retention/util/database.py
All the PRs submitted by Dependabot failed.
When a snapshot repository does not exist, `DROP REPOSITORY` now returns `RepositoryMissingException`.
With previous versions of CrateDB, it was `RepositoryUnknownException`. /cc @SStorm, @faymarie
This patch will make the code accept both variants.
It first happened on GH-38, submitted by Dependabot on Sep 1, 2023.
=> Fix: `DROP REPOSITORY` now returns `RepositoryMissingException`

CHANGES.md, cratedb_toolkit/sqlalchemy/__init__.py, cratedb_toolkit/sqlalchemy/patch.py, cratedb_toolkit/sqlalchemy/polyfill.py, pyproject.toml, tests/sqlalchemy/conftest.py, tests/sqlalchemy/test_patch.py, tests/sqlalchemy/test_polyfill.py
Recent work on unlocking MLflow and LangChain to work together with CrateDB yielded a few patches and polyfills needed to make this happen. A few have been upstreamed into the SQLAlchemy dialect and shipped with the `crate-python` package already, a few others are being added here now, because they do not fit well into the vanilla Python driver / SQLAlchemy dialect.
- https://github.com/crate-workbench/mlflow-cratedb/pull/5
- https://github.com/crate-workbench/langchain/pull/1
- https://github.com/crate/crate-python/pull/582
- https://github.com/crate/crate-python/pull/583
- https://github.com/crate/crate-python/pull/584
=> Contrib: Add a few SQLAlchemy patches and polyfills

.github/workflows/main.yml, CHANGES.md, pyproject.toml
Add Python 3.12 to the list of supported Python releases.
- GH-63
=> Add support for Python 3.12

CHANGES.md, cratedb_toolkit/sqlalchemy/polyfill.py, tests/conftest.py, tests/sqlalchemy/test_polyfill.py
On the SQLAlchemy support subsystem, improve the UNIQUE constraints polyfill to accept multiple column names, for emulating **unique composite keys**.
- https://github.com/crate-workbench/cratedb-toolkit/issues/69
- https://github.com/crate-workbench/mlflow-cratedb/pull/52#pullrequestreview-1708415310
=> SQLAlchemy: Emulate composite unique constraints

.github/workflows/main.yml, pyproject.toml
This is to verify both the minimum and maximum versions of Python to be supported. There are gaps in between, but c'est la view, it saves time and resources.
=> CI: Run on Python 3.8 and 3.12

.github/workflows/main.yml, .gitignore, CHANGES.md, cratedb_toolkit/io/sql.py, cratedb_toolkit/util/database.py, pyproject.toml, tests/io/test_sql.py, tests/retention/test_cli.py
Classical yak shaving.
Similar to https://github.com/pyveci/pueblo/pull/12, this patch adds a generalized testing helper function to avoid code duplication within the educational repository [cratedb-examples](https://github.com/crate/cratedb-examples), originally conceived at [^1]. We need this utility function at many more spots, so we needed to find a good place to store it.
```python
from pprint import pprint
from cratedb_toolkit.io.sql import run_sql
result = run_sql(
dburi="crate://crate@localhost:4200",
sql="SELECT * FROM sys.summits LIMIT 3;",
records=True,
)
pprint(result)
```
Note that details on the interface may change while we go, specifically on the "naming things" / DWIM side of things. If you have any suggestions, feel free to add your voice.
[^1]: …
=> Add SQL runner utility `.io.sql.run_sql`

.github/workflows/main.yml, CHANGES.md, cratedb_toolkit/util/database.py, pyproject.toml, release/oci/Dockerfile, tests/io/test_import.py
More yak shaving.
Similar to https://github.com/pyveci/pueblo/pull/12 and https://github.com/crate-workbench/cratedb-toolkit/pull/74, this patch adds generalized testing helper functions to avoid code duplication within the educational repository [cratedb-examples](https://github.com/crate/cratedb-examples), originally conceived at https://github.com/crate/cratedb-examples/commit/dd09e144ef0. We need those kinds of utility functions at many more spots, so we need to find canonical places to store them.
```shell
pip install 'cratedb-toolkit[io]'
```
```python
from cratedb_toolkit.io.sql import DatabaseAdapter
cratedb = DatabaseAdapter(dburi="crate://crate@localhost:4200")
cratedb.import_csv_pandas(filepath="test.csv", tablename="foobar")
cratedb.import_csv_dask(filepath="test.csv", …
```
=> Add `import_csv_pandas` and `import_csv_dask` utility primitives

cratedb_toolkit/testing/testcontainers/cratedb.py, cratedb_toolkit/testing/testcontainers/util.py
Add generalized `KeepaliveContainer` for efficient use of Testcontainers. It will give all containers the ability to honor `TC_KEEPALIVE=true`, i.e. not shutting down the container after running the test suite. This significantly improves cycle speed.
This generalization to the Testcontainers infrastructure is needed to bring in two subsequent patches, because both will rely on it.
- GH-76
- GH-77
Because both will use this very code to run their test cases, I will not bother to add dedicated test cases for the infrastructure code.
=> Testing: Generalize `KeepaliveContainer` from `CrateDBContainer`

.github/workflows/mongodb.yml, CHANGES.md, cratedb_toolkit/__init__.py, cratedb_toolkit/io/mongodb/README.md, cratedb_toolkit/io/mongodb/cli.py, cratedb_toolkit/io/mongodb/core.py, cratedb_toolkit/io/mongodb/export.py, cratedb_toolkit/io/mongodb/extract.py, cratedb_toolkit/io/mongodb/translate.py, cratedb_toolkit/testing/testcontainers/mongodb.py, doc/sandbox.md, pyproject.toml, tests/io/mongodb/test_cli.py, tests/io/mongodb/test_core.py, tests/io/mongodb/test_extract.py, tests/io/mongodb/test_integration.py, tests/io/mongodb/test_translate.py
The `migr8` program has been maintained over at [^1]. This patch adds it to cratedb-toolkit instead, in order to streamline maintenance in terms of more regular testing and shipping.
Documentation is included. Installation works like:
```shell
pip install 'cratedb-toolkit[io]'
migr8 --help
```
A different CLI/library interface will be added on behalf of a subsequent iteration.
/cc @karynzv
[^1]: https://github.com/crate/mongodb-cratedb-migration-tool
=> MongoDB: Add code from `migr8` program

.github/workflows/influxdb.yml, .github/workflows/main.yml, .gitignore, CHANGES.md, cratedb_toolkit/io/README.md, cratedb_toolkit/io/cli.py, cratedb_toolkit/io/influxdb.py, cratedb_toolkit/testing/testcontainers/cratedb.py, cratedb_toolkit/testing/testcontainers/influxdb2.py, cratedb_toolkit/util/database.py, doc/backlog.md, pyproject.toml, tests/io/influxdb/conftest.py, tests/io/influxdb/test_cli.py
This patch adds an adapter to the [influxio](https://pypi.org/project/influxio/) package, to facilitate data transfers from [InfluxDB v2](https://docs.influxdata.com/influxdb/v2/) and [InfluxDB line protocol](ILP).
```shell
export CRATEDB_SQLALCHEMY_URL=crate://crate@localhost:4200/testdrive/demo
ctk load table influxdb2://example:token@localhost:8086/testdrive/demo
crash --command "SELECT * FROM testdrive.demo;"
```
[InfluxDB line protocol]: https://docs.influxdata.com/influxdb/latest/reference/syntax/line-protocol/
=> InfluxDB: Add adapter to `influxio`, implementing `ctk load table influxdb2://...`

.github/workflows/influxdb.yml, .github/workflows/mongodb.yml, CHANGES.md, cratedb_toolkit/io/README.md, cratedb_toolkit/io/cli.py, cratedb_toolkit/io/influxdb.py, cratedb_toolkit/io/mongodb/README.md, cratedb_toolkit/io/mongodb/api.py, cratedb_toolkit/io/mongodb/cli.py, cratedb_toolkit/io/mongodb/core.py, cratedb_toolkit/io/mongodb/export.py, cratedb_toolkit/io/mongodb/extract.py, cratedb_toolkit/io/mongodb/translate.py, cratedb_toolkit/io/mongodb/util.py, cratedb_toolkit/model.py, cratedb_toolkit/testing/testcontainers/mongodb.py, cratedb_toolkit/testing/testcontainers/util.py, cratedb_toolkit/util/cr8.py, cratedb_toolkit/util/database.py, pyproject.toml, release/oci/Dockerfile, tests/conftest.py, tests/io/influxdb/test_cli.py, tests/io/mongodb/conftest.py, tests/io/mongodb/test_cli.py, tests/io/mongodb/test_extract.py, tests/io/mongodb/test_integration.py, tests/io/mongodb/test_translate.py, tests/io/mongodb/test_util.py, tests/test_model.py
This patch adjusts the MongoDB adapter added with GH-76 to have the same interface like GH-77, in order to facilitate convenient data transfers from [MongoDB](https://github.com/mongodb/mongo).
```shell
export CRATEDB_SQLALCHEMY_URL=crate://crate@localhost:4200/testdrive/demo
ctk load table mongodb://localhost:27017/testdrive/demo
crash --command "SELECT * FROM testdrive.demo;"
```
The patch effectively automates the procedure outlined within the [previous README](https://github.com/crate/mongodb-cratedb-migration-tool/blob/main/README.rst) on behalf of a `mongodb_copy()` primitive.
https://github.com/crate-workbench/cratedb-toolkit/blob/c31df22b59c8019245d55b2bf10496818f3a0ecc/cratedb_toolkit/io/mongodb/api.py#L12-L70
This PR currently can not be reviewed well, because it has multiple …
=> MongoDB: Improve UX by using `ctk load table mongodb://...`

CHANGES.md, cratedb_toolkit/api/guide.py, cratedb_toolkit/api/main.py, cratedb_toolkit/cluster/cli.py, cratedb_toolkit/exception.py, cratedb_toolkit/io/README.md, cratedb_toolkit/io/cli.py, cratedb_toolkit/io/croud.py, cratedb_toolkit/model.py, cratedb_toolkit/retention/store.py, cratedb_toolkit/util/croud.py, doc/backlog.md, examples/cloud_import.py, pyproject.toml, release/oci/Dockerfile, tests/conftest.py, tests/io/test_import.py, tests/retention/test_examples.py
- Data loading: Refactor to use more OO.
- Data model, naming things, error handling, croud workarounds.
- Add `examples/cloud_import.py`.
=> Data loading: Refactor to use more OO. Add `examples/cloud_import.py`.

cratedb_toolkit/testing/testcontainers/cratedb.py, doc/sandbox.md, pyproject.toml, tests/conftest.py, tests/testing/test_testcontainers.py
Testing: Adapt "Testcontainers" implementation to `unittest`
- GH-58
- https://github.com/crate/crash/pull/408
=> Adapt testcontainers to be testing framework agnostic

.github/workflows/main.yml, CHANGES.md, cratedb_toolkit/api/main.py, cratedb_toolkit/cluster/util.py, cratedb_toolkit/job/cli.py, cratedb_toolkit/util/croud.py, pyproject.toml
Don't install `croud` by default. It will not work on Python 3.7.
- Problem: https://github.com/crate/crash/actions/runs/7588894584/job/20672385743?pr=408
- Unblocks: https://github.com/crate/crash/pull/408.
=> Packaging: Use `cloud` extra to install relevant packages

.github/workflows/influxdb.yml, .github/workflows/main.yml, .github/workflows/mongodb.yml
`codecov-action@v4` has issues, it apparently does not upload without token any longer.
This reverts commit e4df24e8b13910d6707ae14ddfeaa9ffe0d2cf53.
- https://github.com/crate-workbench/cratedb-toolkit/pull/109
=> Revert "Bump codecov/codecov-action from 3 to 4"

codecov.yml, doc/sandbox.md
Without it some test fail when running all.
=> Sandbox: Add `all` extra to dev install command

.gitignore, cratedb_toolkit/testing/pytest.py, pyproject.toml, tests/conftest.py, tests/testing/test_pytest.py
Export `cratedb_service` fixture as pytest11 entrypoint.
This way, for basic needs, corresponding boilerplate code does not need to be provided by downstream projects.
When needing more configurability, you will need to define corresponding alternative fixtures, and not use the built-in provided from.
=> Testing: Export `cratedb_service` fixture as pytest11 entrypoint

CHANGES.md, cratedb_toolkit/datasets/README.md, cratedb_toolkit/datasets/__init__.py, cratedb_toolkit/datasets/core.py, cratedb_toolkit/datasets/model.py, cratedb_toolkit/datasets/store.py, cratedb_toolkit/datasets/tutorial.py, cratedb_toolkit/util/database.py, pyproject.toml, tests/datasets/conftest.py, tests/datasets/test_tutorials.py, tests/sqlalchemy/test_patch.py
Provide access to datasets, to be easily consumed by tutorials
and/or production applications.
```python
from cratedb_toolkit.datasets import load_dataset
dataset = load_dataset("tutorial/weather-basic")
dataset.to_cratedb(dburi="crate://crate@localhost/", table="weather_data")
```
- https://github.com/crate-workbench/cratedb-toolkit/issues/89
- https://github.com/crate/cratedb-datasets/pull/9
=> Add `cratedb_toolkit.datasets` subsystem

cratedb_toolkit/datasets/kaggle.py
Adding SQL DDL for [The Weather Dataset](https://www.kaggle.com/datasets/guillemservera/global-daily-climate-data) on Kaggle, specifically for the schema of the `cities.csv` file, which has been forgotten.
=> cratedb_toolkit.datasets: Add DDL schema for The Weather Dataset: Cities

CHANGES.md, pyproject.toml
```python
>           import dask_expr  # noqa: F401
E           ModuleNotFoundError: No module named 'dask_expr'
```
-- https://github.com/crate-workbench/cratedb-toolkit/actions/runs/8258902237/job/22591947853#step:5:43
- https://github.com/daq-tools/influxio/pull/85
- https://github.com/microsoft/LightGBM/issues/6365
- https://github.com/microsoft/LightGBM/pull/6357
=> Dependencies: Use `dask[dataframe]`

CHANGES.md, pyproject.toml, tests/io/influxdb/test_cli.py
Otherwise, compatibility issues can not be resolved quickly, like with Python 3.11.9.
- https://github.com/dask/dask/issues/11038
- https://github.com/pycaret/pycaret/issues/3960#issuecomment-2045881422
=> Dependencies: Unpin upper version bound of `dask`

CHANGES.md, pyproject.toml
Use more recent influxio package, which resolves a problem when connecting to CrateDB Cloud, by propagating `ssl=true` query argument.
Update dependencies to `influxio>=0.2.1,<1`.
- https://github.com/daq-tools/influxio/issues/125
=> Fix InfluxDB Cloud <-> CrateDB Cloud connectivity

CHANGES.md, cratedb_toolkit/api/main.py, cratedb_toolkit/testing/testcontainers/util.py, cratedb_toolkit/util/data.py, doc/io/influxdb/loader.md
... by using `ssl=true` query argument also for `influxdb2://` source URLs.
A preview: https://cratedb-toolkit--154.org.readthedocs.build/io/influxdb/loader.html#cloud
- A follow-up to GH-152
=> Fix InfluxDB Cloud <-> CrateDB Cloud connectivity once more

.github/workflows/influxdb.yml, .github/workflows/main.yml, .github/workflows/mongodb.yml
The reason is because free capacity for Codecov uploads is limited, currently starting to trip on the 20th of each month, due to nightly usage. This patch follows up on 2554a50c9a, by steering the workaround for this edge case into a different direction.
=> CI: Run nightly testing jobs each second night only

CHANGES.md, cratedb_toolkit/sqlalchemy/patch.py, cratedb_toolkit/testing/pytest.py, cratedb_toolkit/util/common.py, cratedb_toolkit/util/database.py, pyproject.toml, tests/conftest.py
The [CrateDB SQLAlchemy dialect](https://github.com/crate-workbench/sqlalchemy-cratedb) needs more love, so it was separated from the [DBAPI HTTP driver](https://github.com/crate/crate-python). This patch verifies and concludes the migration.
- https://github.com/crate/roadmap/issues/85
=> Dependencies: Migrate from `crate[sqlalchemy]` to `sqlalchemy-cratedb`

cratedb_toolkit/cfr/cli.py, cratedb_toolkit/cfr/systable.py, tests/cfr/test_cli.py
Some CFR improvements:
- Add support to directly export the system tables into a `tgz` file
=> cfr: Add support to directly export to an archive file

CHANGES.md, cratedb_toolkit/sqlalchemy/__init__.py, cratedb_toolkit/sqlalchemy/patch.py, pyproject.toml, tests/sqlalchemy/test_patch.py
The new designated CrateDB SQLAlchemy dialect, `sqlalchemy-cratedb`, now includes the fix to the `get_table_names()` reflection method, which has been living as a monkeypatch variant here for a while. @surister supported us to provide test cases to the new upstream package. Thanks.
- https://github.com/crate-workbench/sqlalchemy-cratedb/pull/10
- https://github.com/daq-tools/influxio/pull/128
=> SQLAlchemy Dialect: Dependencies: Use `sqlalchemy-cratedb>=0.37`

cratedb_toolkit/cfr/systable.py, cratedb_toolkit/testing/testcontainers/cratedb.py, cratedb_toolkit/util/database.py, tests/cfr/test_cli.py, tests/util/database.py
=> Use sqlalchemy's 'quote' function to quote table names and fix table quoting in cfr exporter

.github/workflows/release-oci.yml, .github/workflows/release-pypi.yml, doc/index.md, doc/release.md
Automate the PyPI release procedure by staging packages through GHA.
- The GHA recipe is derived from `sqlalchemy-cratedb`'s [release.yml](https://github.com/crate-workbench/sqlalchemy-cratedb/blob/main/.github/workflows/release.yml).
- The `PYPI_API_TOKEN` variable has been added to the [secrets section](https://github.com/crate-workbench/cratedb-toolkit/settings/secrets/actions) of this repository.
=> CI: Add GHA workflow recipe for staging packages to PyPI, `release-pypi.yml`

CHANGES.md, doc/io/influxdb/loader.md, pyproject.toml
Because the InfluxDB I/O subsystem, implementing `ctk load table influxdb2://...`, always replaced the target table, it could have been considered as "just a toy". Thanks to that discovery by @wierdvanderhaar, we have been able to improve it.
The improvement follows the semantics of the [`to_sql()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html) implementation of pandas/Dask, and now takes a new `if-exists` URL query parameter into consideration, forwarding the possible values `{fail,replace,append}` to the corresponding implementation.
- GH-148
- https://github.com/daq-tools/influxio/pull/129
/cc @matkuliak, @simonprickett
=> IO: Add the `if-exists` query parameter by updating to influxio 0.4.0

cratedb_toolkit/cfr/systable.py, tests/conftest.py, tests/io/influxdb/test_cli.py, tests/io/mongodb/conftest.py, tests/io/mongodb/test_cli.py, tests/io/mongodb/test_integration.py, tests/io/test_import.py, tests/retention/conftest.py, tests/retention/test_cli.py, tests/retention/test_examples.py, tests/retention/test_store.py, tests/sqlalchemy/test_patch.py, tests/sqlalchemy/test_polyfill.py, tests/testing/test_cratedb_sqlalchemy.py
Broken away from GH-83. Makes running tests on both SQLAlchemy 1 and SQLAlchemy 2 easier, because the test cases now know what is acceptable for them.
=> Testing: Add pytest fixtures to discriminate between SQLAlchemy 1 and 2

.github/dependabot.yml, .github/workflows/release-oci.yml, .github/workflows/release-pypi.yml
- Increase frequency of Dependabot checks to "weekly".
- Naming things. Use `Release:` prefix for all release jobs.
=> CI: Maintenance, this and that

.github/workflows/release-app.yml, CHANGES.md, cratedb_toolkit/cfr/cli.py, pyproject.toml
Use [PyInstaller](https://pyinstaller.org/) to build self-contained application bundles of the [CrateDB Cluster Flight Recorder (CFR)](https://cratedb-toolkit.readthedocs.io/cfr/).
- GH-160
See section "Artifacts » Produced during runtime" on [GHA run #9826830191](https://github.com/crate-workbench/cratedb-toolkit/actions/runs/9826830191).
=> Add support to publish cfr as a binary using PyInstaller

cratedb_toolkit/adapter/pymongo/cursor.py, cratedb_toolkit/util/database.py, doc/io/influxdb/loader.md, pyproject.toml, tests/adapter/test_pymongo.py
What the title says: Nothing serious, nor specific.
=> Chore: Satisfy linter, add inline comments, improve documentation

.github/workflows/main.yml, .github/workflows/release-app.yml
Check why GH-196 fails, and resolve it.
Fails on Python 3.8, with setuptools 70.3.0.
-- https://github.com/crate/cratedb-toolkit/actions/runs/9982521975/job/27589490156?pr=196#step:6:229
```
/path/to/lib/python3.8/site-packages/setuptools/_vendor/jaraco/context.py:17: ImportError
```
```python
ImportError: cannot import name 'tarfile' from 'backports' (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/backports/__init__.py)
```
Fails on all test matrix slots.
```
PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_importlib_metadata required by hook for module /opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/PyInstaller/hooks/hook-importlib_metadata.py. Please check whether module …
```
=> Setup: Fix package installation woes with `setuptools`/`backports.tarfile`, and `PyInstaller`

cratedb_toolkit/model.py, cratedb_toolkit/util/database.py, tests/util/database.py
Just a bit of refactoring and infrastructure improvements.
By making the canonical `DatabaseAdapter.quote_relation_name` static,  it can be used by `TableAddress.fullname` now.
This makes table name quoting less fragmented across the code base.
- https://github.com/crate/cratedb-toolkit/pull/196#discussion_r1684982717
We need it for GH-196, and we need to ship it. Please add your voice retroactively, so we can consider any admonitions from your pen even after this has been merged already. Thank you!
=> Core: Improve quoting for `TableAddress.fullname`

CHANGES.md, pyproject.toml
- CI trips on GH-205.
- https://github.com/Kaggle/kaggle-api/issues/611
Fix dependency with the `kaggle` package, downgrade to `kaggle==1.6.14`.
```
The most likely cause of this is that there is no directory that matches the name of your project (kaggle).
```
Most probably, this is coming from switching to Hatch?
=> Dependencies: Downgrade to `kaggle==1.6.14`

cratedb_toolkit/iac/aws.py, cratedb_toolkit/io/processor/kinesis_lambda.py, doc/io/dynamodb/cdc.md, doc/io/dynamodb/index.md, doc/io/index.md, examples/aws/dynamodb_kinesis_lambda_oci_cratedb.py, pyproject.toml
To support people using CrateDB together with infrastructure components managed on other people's computers more easily.
Preview: https://cratedb-toolkit--205.org.readthedocs.build/io/dynamodb/cdc.html
A little insight into the nitty gritty details. Currently, we are focusing on AWS Lambda to use as an on-demand compute environment, but the fundamental infrastructure is aiming to be generic enough to work on other kinds of compute environments as well.
This makes a start by processing CDC events from DynamoDB, in order to re-materialize them into a CrateDB table.
The subsystem bears a few generic components to build upon, still in its infancy, but also suitable for similar operations on other data sources.
- A convenient [Infrastructure as code …
=> DynamoDB CDC: Add demo to support reading DynamoDB change data capture

CHANGES.md, cratedb_toolkit/io/processor/kinesis_lambda.py, pyproject.toml
Building upon the DynamoDB CDC implementation, this pulls the most recent Amazon Kinesis -> CrateDB pipeline element (downstream processor, AWS Lambda flavour) from upstream, so that processing messages from AWS DMS works.
- GH-205
- https://github.com/daq-tools/lorrystream/pull/120
=> Processor: Update Kinesis Lambda processor to understand AWS DMS

CHANGES.md, cratedb_toolkit/api/main.py, cratedb_toolkit/io/cli.py, cratedb_toolkit/io/mongodb/api.py, cratedb_toolkit/io/mongodb/cli.py, cratedb_toolkit/io/mongodb/core.py, cratedb_toolkit/io/mongodb/export.py, cratedb_toolkit/io/mongodb/extract.py, cratedb_toolkit/io/mongodb/transform.py, cratedb_toolkit/io/mongodb/translate.py, cratedb_toolkit/io/mongodb/util.py, cratedb_toolkit/util/data_dict.py, doc/io/mongodb/loader.md, doc/io/mongodb/migr8.md, examples/zyp-transformation.yaml, pyproject.toml
The venerable migr8 program did not receive much love to get the details right. This patch intends to catch up on this, in order to make [`ctk load table mongodb://...`](https://cratedb-toolkit.readthedocs.io/io/mongodb/loader.html) hold up to its promise of better [DWIM](https://en.wikipedia.org/wiki/DWIM).
```shell
pip install --upgrade 'cratedb-toolkit[mongodb] @ git+https://github.com/crate/cratedb-toolkit.git@mongodb-better-1'
```
`Exception: Can't parse datetime string 2022-06-11T04:37:53.200Z`
GH-215
- MongoDB: Fix missing output on STDOUT for `migr8 export`
- MongoDB: Improve timestamp parsing by using `python-dateutil`
- MongoDB: Converge `_id` input field to `id` column instead of dropping it
- MongoDB: Make user interface use stderr, so stdout is for data only
- MongoDB: Make …
=> MongoDB: Various fixes and improvements

pyproject.toml
Installation fails with:
```
Running command git clone --filter=blob:none --quiet https://github.com/daq-tools/lorrystream.git 'C:\Users\Hernan\AppData\Local\Temp\pip-install-qb60dek8\lorrystream_4805b8717a3c400e8e6fb2eb16e6e0bd'
WARNING: Did not find branch or tag '55cf456fdcd3', assuming revision or ref.
```
Then branched cratedb-toolkit and tried making it point to different points in the lorrystream tree (the kinesis branch - the beginning of the kinesis branch - the main branch at the point of toolkit 0.0.16 release) the main branch does not know about carabas, the other 2 also failed with different errors.
Thanks for reporting, @hlcianfagna!
=> Chore: Fix reference to LorryStream WIP

.github/workflows/main.yml, CHANGES.md, cratedb_toolkit/iac/aws.py, cratedb_toolkit/io/processor/kinesis_lambda.py, pyproject.toml, release/oci/Dockerfile, tests/io/test_iac.py, tests/io/test_processor.py
On the last occasion, dependencies to lorrystream have not been verified correctly, so it was expectable that things go south at some point. Pinning to a branch, or pinning to a specific commit, are both not satisfying solutions to compensate properly for aligning things that are in flux by nature. C'est la vie.
This patch fixes them, and adds rudimentary software tests to avoid tripping into the same situation as before.
- https://github.com/crate/cratedb-toolkit/issues/222
/cc @wierdvanderhaar, @surister, @ckurze
=> Dependencies: Update to lorrystream 0.0.4 and commons-codec 0.0.6. Adjust code. Add software tests.

.github/workflows/dynamodb.yml, CHANGES.md, cratedb_toolkit/api/main.py, cratedb_toolkit/io/dynamodb/adapter.py, cratedb_toolkit/io/dynamodb/api.py, cratedb_toolkit/io/dynamodb/backlog.md, cratedb_toolkit/io/dynamodb/copy.py, cratedb_toolkit/io/processor/kinesis_lambda.py, cratedb_toolkit/testing/testcontainers/localstack.py, cratedb_toolkit/testing/testcontainers/util.py, doc/io/dynamodb/index.md, doc/io/dynamodb/loader.md, pyproject.toml, tests/io/dynamodb/README.md, tests/io/dynamodb/__init__.py, tests/io/dynamodb/conftest.py, tests/io/dynamodb/manager.py, tests/io/dynamodb/productcatalog.json, tests/io/dynamodb/test_cli.py, tests/io/dynamodb/test_import.py
Bring DynamoDB full-load to Toolkit's `ctk load table` interface. 
https://cratedb-toolkit--226.org.readthedocs.build/io/dynamodb/loader.html
Alpha. For now, the implementation uses the same easy strategy to converge the source record into a single `data (OBJECT)` column in CrateDB. The 1:1 strategy may follow.
- GH-231
/cc @hammerhead, @zolbatar
=> DynamoDB: Add table loader for full-load operations

CHANGES.md, cratedb_toolkit/io/processor/kinesis_lambda.py, pyproject.toml
=> Dependencies: Unpin commons-codec, to always use the latest version

CHANGES.md, pyproject.toml
=> Dependencies: Unpin lorrystream, to always use the latest version

CHANGES.md, cratedb_toolkit/io/mongodb/extract.py, tests/io/mongodb/test_extract.py
@matkuliak reported that the MongoDB I/O subsystem wasn't capable to map values like `Long('1563051934000')` to CrateDB SQL's `BIGINT` data type.
- GH-219
This patch improves the situation.
=> MongoDB: Improve type mapper discriminating between INTEGER and BIGINT

CHANGES.md, cratedb_toolkit/io/mongodb/extract.py, tests/io/mongodb/test_extract.py
Add support for more BSON types to the MongoDB type mapper: DatetimeMS, Decimal128, Int64.
=> MongoDB: Improve type mapper, add support for more BSON types

cratedb_toolkit/io/mongodb/extract.py, cratedb_toolkit/io/mongodb/translate.py, tests/io/mongodb/test_extract.py, tests/io/mongodb/test_translate.py
The MongoDB type mapper now honors more types.
- DECIMAL => DOUBLE
- INT64 => BIGINT
- TIMESTAMP => TIMESTAMP WITHOUT TIME ZONE
=> MongoDB: Improve type mapper in schema translator

CHANGES.md, cratedb_toolkit/io/processor/kinesis_lambda.py
Easily fix missing table quoting within CDC processor for DMS and DynamoDB events. It will need more improvements by adding the canonical implementation [quote_relation_name](https://github.com/crate/cratedb-toolkit/blob/v0.0.19/cratedb_toolkit/util/database.py#L44-L80) to sqlalchemy-cratedb, but may be good for now.
=> DMS/DynamoDB: Fix table name quoting within CDC processor handler

tests/io/dynamodb/manager.py, tests/io/dynamodb/test_copy.py
People reported problems converging a list of objects from DynamoDB to CrateDB. Adding a test case to evaluate the situation.
- https://github.com/crate/commons-codec/pull/37
=> DynamoDB: Add software test for decoding list of objects

.github/workflows/dynamodb.yml, tests/io/dynamodb/test_copy.py
Validating another test case with a list including a single item, which is an empty string.
Thanks for reporting, @wierdvanderhaar.
=> DynamoDB: Improve software test about decoding a list with empty string

.github/workflows/influxdb.yml, .github/workflows/main.yml, .github/workflows/mongodb.yml
Codecov API was down, now it's back up.
This reverts commit 12a624f87f411dd1b1206d3b3ce5293d3be9360a.
=> Revert "CI: Codecov API is currently down"

.github/workflows/dynamodb.yml, CHANGES.md, cratedb_toolkit/io/dynamodb/adapter.py, cratedb_toolkit/io/dynamodb/copy.py, cratedb_toolkit/io/processor/kinesis_lambda.py, cratedb_toolkit/testing/testcontainers/localstack.py, doc/io/dynamodb/loader.md, pyproject.toml, tests/io/dynamodb/test_adapter.py, tests/io/dynamodb/test_cli.py, tests/io/dynamodb/test_copy.py
For making DynamoDB `full-load` operations more efficient, use [CrateDB's bulk operations](https://cratedb.com/docs/crate/reference/en/latest/interfaces/http.html#bulk-operations). With this patch, the batching towards CrateDB is implemented by doing pagination on the DynamoDB source database. For other strategies, see backlog.
- https://github.com/crate/cratedb-toolkit/issues/249
- https://github.com/crate/commons-codec/pull/43
For subsequent iterations:
- GH-231
/cc @wierdvanderhaar, @hlcianfagna
=> DynamoDB: Add pagination support for `full-load` table loader

CHANGES.md, cratedb_toolkit/api/main.py, cratedb_toolkit/io/cli.py, cratedb_toolkit/io/mongodb/adapter.py, cratedb_toolkit/io/mongodb/api.py, cratedb_toolkit/io/mongodb/copy.py, cratedb_toolkit/model.py, cratedb_toolkit/util/database.py, doc/io/mongodb/loader.md, tests/io/mongodb/test_copy.py
A few features that have not been ready (lacked software tests) to be included into GH-255.
- Unlock processing multiple collections, either from server database, or from filesystem directory
- Unlock processing JSON files from HTTP resource, using `https+bson://`
- Optionally filter server collection using MongoDB query expression
https://cratedb-toolkit--261.org.readthedocs.build/io/mongodb/loader.html
```
pip install --upgrade 'cratedb-toolkit[mongodb] @ git+https://github.com/crate/cratedb-toolkit.git@amo/mongodb-more-2'
```
=> MongoDB: Improve support for reading JSON/BSON files

CHANGES.md, cratedb_toolkit/io/core.py, cratedb_toolkit/io/mongodb/api.py, cratedb_toolkit/io/mongodb/copy.py, cratedb_toolkit/sqlalchemy/patch.py, pyproject.toml, tests/io/mongodb/mixed.ndjson, tests/io/mongodb/test_copy.py
In order to have both, efficient bulk insert operations, and on-the-spot error messages on records that fail to insert, let's introduce a two-stage approach:
- First, try to insert a batch.
- When it fails, determine invalid records and insert them one-by-one, in order to relay corresponding error messages to the user.
`BulkProcessor` rips the canonical implementation off the specific handler about MongoDB I/O, setting the stage to reuse it on other I/O subsystems as well. Improving error handling has already been requested for the DynamoDB table loader, so applying the outcome there will certainly be next.
- Related: https://github.com/crate/crate/issues/16617
- Predecessor: GH-261
/cc @juanpardo
=> MongoDB: Improve error handling wrt. bulk operations vs. usability

.github/workflows/dynamodb.yml, CHANGES.md, cratedb_toolkit/api/main.py, cratedb_toolkit/io/dynamodb/adapter.py, cratedb_toolkit/io/dynamodb/copy.py, cratedb_toolkit/io/kinesis/adapter.py, cratedb_toolkit/io/kinesis/api.py, cratedb_toolkit/io/kinesis/relay.py, doc/io/dynamodb/cdc-lambda.md, doc/io/dynamodb/cdc.md, doc/io/dynamodb/index.md, doc/io/dynamodb/loader.md, examples/aws/kinesis_put.py, pyproject.toml, tests/io/dynamodb/conftest.py, tests/io/dynamodb/test_adapter.py, tests/io/dynamodb/test_cli.py, tests/io/dynamodb/test_copy.py, tests/io/dynamodb/test_relay.py, tests/io/test_processor.py
Running DynamoDB CDC events through Kinesis and processing them using an AWS Lambda is cumbersome more often than not, and not too suitable for collaboration and development purposes. This patch provides a standalone implementation, as a sister to the corresponding full-load implementation, [DynamoDB Table Loader](https://cratedb-toolkit.readthedocs.io/io/dynamodb/loader.html).
Preview: https://cratedb-toolkit--247.org.readthedocs.build/io/dynamodb/cdc.html
Use AWS for real, or exercise using LocalStack.
```shell
export CRATEDB_SQLALCHEMY_URL=crate://crate@localhost:4200/testdrive/demo
ctk load table kinesis+dynamodb+cdc://AWS_ACCESS_KEY:AWS_SECRET_ACCESS_KEY@aws/cdc-stream?region=us-east-1
ctk load table kinesis+dynamodb+cdc://LSIAQAAAAAAVNCBMPNSG:dummy@localhost:4566/cdc-stream?region=eu …
```
=> DynamoDB: Add `ctk load table` interface for processing CDC events

doc/io/dms/index.md, doc/io/dms/managed.md, doc/io/dms/standalone.md, doc/io/index.md
Coming from https://github.com/daq-tools/lorrystream/pull/120, this patch intends to unlock relevant details about using AWS DMS together with CrateDB and CrateDB Cloud in CrateDB Toolkit.
https://cratedb-toolkit--213.org.readthedocs.build/io/dms/
- https://github.com/crate/cratedb-guide/pull/115
/cc @ckurze
=> AWS DMS: Add first working version

CHANGES.md, cratedb_toolkit/api/main.py, cratedb_toolkit/io/cli.py, cratedb_toolkit/io/core.py, cratedb_toolkit/io/mongodb/adapter.py, cratedb_toolkit/io/mongodb/api.py, cratedb_toolkit/io/mongodb/copy.py, cratedb_toolkit/io/mongodb/core.py, cratedb_toolkit/io/mongodb/transform.py, cratedb_toolkit/io/mongodb/util.py, cratedb_toolkit/util/cli.py, cratedb_toolkit/util/common.py, cratedb_toolkit/util/io.py, doc/backlog.md, doc/io/mongodb/loader.md, pyproject.toml, tests/io/mongodb/test_copy.py
A few refinements, here and there, mostly about `ctk load table` and the MongoDB I/O adapter.
- Table Loader: Improve conditional handling of "transformation" parameter
- Table Loader: Improve status reporting + error logging in BulkProcessor
- MongoDB Adapter: Improve error reporting
- MongoDB Adapter: Improve performance of collection cardinality gathering
- MongoDB Adapter: Evaluate filtering by `_id` by casting to bson.ObjectId
- MongoDB Full: Polars' `read_ndjson` doesn't load MongoDB JSON data well
- MongoDB Full: Improve initialization of transformation subsystem
- MongoDB Full: Use `limit` parameter as number of total records
- MongoDB Full: Improve documentation
=> Table Loader and MongoDB: A few refinements

CHANGES.md, cratedb_toolkit/io/mongodb/copy.py, pyproject.toml
commons-codec 0.0.18 provides configuration capabilities about how to decode timestamp values. CTK currently uses this configuration, in order to emit timestamp values in milliseconds since epoch, suitable to be stored as BIGINT.
```python
MongoDBCrateDBConverter(
timestamp_to_epoch=True,
timestamp_use_milliseconds=True,
)
```
Alternatively, you can configure it to emit timestamps in ISO8601 format, suitable to be stored as STRING.
```python
MongoDBCrateDBConverter(
timestamp_to_iso8601=True,
)
```
/cc @hlcianfagna, @wierdvanderhaar
=> MongoDB: Configure `MongoDBCrateDBConverter` for updating commons-codec

CHANGES.md, cratedb_toolkit/io/kinesis/relay.py, pyproject.toml, tests/io/dynamodb/test_relay.py, tests/io/test_processor.py
> Hey guys, I noticed earlier that DynamoDB updates that removed fields from items were not synced properly to CrateDB, would you know why?
- https://github.com/crate/commons-codec/pull/60
- https://github.com/crate/commons-codec/releases/tag/v0.0.19
=> DynamoDB CDC: Make MODIFY operation also propagate deleted attributes

CHANGES.md, cratedb_toolkit/io/dynamodb/adapter.py, cratedb_toolkit/io/dynamodb/copy.py, cratedb_toolkit/io/processor/kinesis_lambda.py, pyproject.toml, tests/io/dynamodb/test_copy.py, tests/io/dynamodb/test_relay.py, tests/io/test_processor.py
By breaking the primary key information out of the main record's data bucket, the main record can be updated as-is on CDC MODIFY operations.
- https://github.com/crate/commons-codec/pull/64
=> DynamoDB: Change CrateDB data model to use (`pk`, `data`, `aux`) columns

CHANGES.md, cratedb_toolkit/testing/testcontainers/util.py
Pulling the OCI each time again is unfortunate in disconnected situations. Let's stop doing it.
=> Testcontainers: Don't always pull the OCI image before starting.

CHANGES.md, cratedb_toolkit/api/main.py, cratedb_toolkit/io/mongodb/adapter.py, cratedb_toolkit/io/mongodb/api.py, cratedb_toolkit/io/mongodb/cdc.py, cratedb_toolkit/testing/testcontainers/mongodb.py, cratedb_toolkit/util/process.py, doc/io/mongodb/cdc.md, doc/io/mongodb/loader.md, tests/io/mongodb/conftest.py, tests/io/mongodb/test_cdc.py, tests/util/processor.py
Make the CDC subsystem more symmetric to the full-load procedure.
```
pip install 'cratedb-toolkit[mongodb,zyp] @ git+https://github.com/crate/cratedb-toolkit.git@mongodb-cdc-transformations'
```
Minimal variant. Preview.
- https://cratedb-toolkit--288.org.readthedocs.build/io/mongodb/cdc.html#transformations
=> MongoDB: Add Zyp transformations to CDC subsystem

CHANGES.md, codecov.yml, cratedb_toolkit/cli.py, cratedb_toolkit/query/cli.py, cratedb_toolkit/query/convert/basic.py, cratedb_toolkit/query/convert/cli.py, doc/index.md, doc/query/convert.md, doc/query/index.md, tests/query/test_convert.py
DynamoDB: Added query expression converter for relocating object references, to support query migrations after the breaking change with the SQL DDL schema, by [v0.0.27](https://github.com/crate/cratedb-toolkit/releases/tag/v0.0.27).
```shell
echo "SELECT * FROM foobar WHERE data['PK']" > input.sql
ctk query convert --type=ddb-relocate-pks --primary-keys=PK,SK input.sql > output.sql
cat output.sql
```
```sql
SELECT * FROM foobar WHERE pk['PK']
```
https://cratedb-toolkit--289.org.readthedocs.build/query/convert.html
```
pip install 'cratedb-toolkit @ git+https://github.com/crate/cratedb-toolkit.git@query-converter'
```
=> Query Converter: Add very basic expression converter utility with CLI

.github/workflows/main.yml, CHANGES.md, cratedb_toolkit/cfr/systable.py, pyproject.toml, tests/cfr/test_cli.py
Make `polars` not install by default.
- Defer `polars` to `cratedb-toolkit[io]` and `cratedb-toolkit[cfr]`
- Add dedicated testing slot for CrateDB CFR
=> Dependencies: Minimize dependencies of core installation

CHANGES.md, cratedb_toolkit/wtf/core.py, doc/wtf/index.md
Store `ulimit_hard` as STRING instead of BIGINT.
```
{
"ulimit_soft": 256,
"ulimit_hard": "9223372036854775807"
}
```
/cc @WalBeh
=> Fix `cratedb-wtf record` about too large values of `ulimit_hard`

CHANGES.md, cratedb_toolkit/cli.py, cratedb_toolkit/cmd/tail/cli.py, cratedb_toolkit/cmd/tail/main.py, cratedb_toolkit/util/database.py, doc/cmd/index.md, doc/index.md, doc/wtf/index.md, tests/cmd/test_tail.py
Implement `tail -f` for `sys.jobs_log`, to support ad hoc tracing of SQL statements processed by CrateDB.
```shell
export CRATEDB_SQLALCHEMY_URL=crate://crate@localhost:4200/
```
```shell
ctk tail -n 3 --follow --format=log-pretty sys.jobs_log
crash -c "SELECT * FROM sys.summits LIMIT 3;"
```
The implementation may be versatile enough to also work well on arbitrary tables.
```shell
ctk tail -n 3 sys.summits
```
- https://cratedb-toolkit--330.org.readthedocs.build/cmd/
- https://cratedb-toolkit--330.org.readthedocs.build/wtf/#one-shot-commands
- GH-171
=> Add basic utility command `ctk tail`, for tailing a database table and optionally following the tail

CHANGES.md, cratedb_toolkit/api/main.py, cratedb_toolkit/io/influxdb.py, doc/io/influxdb/loader.md, pyproject.toml, tests/io/influxdb/test_cli.py
Improve the InfluxDB table loader adapter by directly loading ILP files.
```shell
ctk load table "file://influxdb-export.lp"
```
```shell
ctk load table \
"https://github.com/influxdata/influxdb2-sample-data/raw/master/air-sensor-data/air-sensor-data.lp"
```
Preview: https://cratedb-toolkit--333.org.readthedocs.build/io/influxdb/loader.html#line-protocol-file-ilp
- GH-268
- https://github.com/crate/cratedb-examples/pull/783
- https://github.com/crate/cratedb-guide/pull/170
- GH-77
- GH-154
- GH-176
/cc @karynzv, @hlcianfagna, @hammerhead, @wierdvanderhaar, @surister, @simonprickett, @kneth
=> Table Loader: Add capability to load InfluxDB Line Protocol (ILP) files

doc/io/index.md
We can't trust GitHub for access to LFS files directly when running `COPY FROM` statements, so this changes the URLs to point to their replacements.
=> Replaced old references to cratedb-datasets repo with new CrateDB URLs.

examples/cloud_import.py
Fixed example `COPY FROM` URLs to point to the new location.
=> Updated dataset loading URLs

cratedb_toolkit/datasets/tutorial.py, doc/bugs.md
Along the lines of GH-339, GH-340, GH-341, to update the dataset URLs to the new location at https://cdn.crate.io/downloads/datasets/cratedb-datasets/.
=> cratedb-datasets: Updated URL to new location for Python Datasets API

CHANGES.md, cratedb_toolkit/wtf/query_collector.py, tests/wtf/test_cli.py
`ctk wtf job-statistics collect` did not respect the `CRATEDB_SQLALCHEMY_URL` environment variable yet. Now, it does, and by that, it will also make the table schema configurable.
=> Query Collector: Respect `CRATEDB_SQLALCHEMY_URL` environment variable

CHANGES.md, cratedb_toolkit/cfr/systable.py, cratedb_toolkit/util/sqlalchemy.py, pyproject.toml, tests/sqlalchemy/test_patch.py
Validate and bring in an improvement to crate-python.
- https://github.com/crate/crate-python/pull/691
- https://github.com/crate/crash/pull/459
- https://github.com/crate/sqlalchemy-cratedb/pull/195
=> Update to `crate-2.0.0`, which uses `orjson` for JSON marshalling

pyproject.toml, tests/sqlalchemy/test_patch.py
The fundamental patch GH-349 needs a little update, pulling in a more recent pre-release version of crate-python.
- https://github.com/crate/crate-python/pull/691
=> Dependencies: Update to `crate>=2.0.0.dev6`, restoring JSON marshalling

cratedb_toolkit/datasets/tutorial.py
By providing a little API that wraps SQL loader snippets of [cratedb-datasets](https://github.com/crate/cratedb-datasets), it becomes easier to load the Chicago datasets programmatically.
- https://github.com/crate/cratedb-datasets/pull/27
/cc @simonprickett
=> Datasets: Register Chicago datasets

pyproject.toml
Update to most recent crate 2.0.0 and sqlalchemy-cratedb 0.41.0.
- https://github.com/crate/crate-python/issues/693
=> Dependencies: Update to sqlalchemy-cratedb>=0.41.0 (GA)

CHANGES.md, cratedb_toolkit/cfr/cli.py, cratedb_toolkit/cfr/marimo.py, doc/cfr/jobstats.md, pyproject.toml
A little UI including a few elements for the [jobstats](https://cratedb-toolkit.readthedocs.io/cfr/jobstats.html) subsystem of [CFR](https://cratedb-toolkit.readthedocs.io/cfr/), and a widget for exploring slow queries.
All is mostly made using marimo's native data table elements, feeding them from pandas data frames, and adds a little bit of interactivity where applicable.
=> CFR job statistics and slow-query exploration: First draw of marimo notebook

pyproject.toml
... for poethepoet and validate-pyproject. Their interfaces are considered stable enough.
Aiming to make GH-380 and GH-381 and future instances obsolete.
=> Dependencies: Relax version constraints for development tools

.github/workflows/influxdb.yml, .github/workflows/main.yml, .github/workflows/mongodb.yml
Due to a recent hiccup with a fundamental software package in the Python ecosystem.
- https://github.com/fsspec/filesystem_spec/issues/1816
=> CI: Add software testing for Python 3.8 and 3.9

.github/workflows/main.yml, CHANGES.md, cratedb_toolkit/query/cli.py, cratedb_toolkit/query/mcp/cli.py, cratedb_toolkit/query/mcp/inquiry.py, cratedb_toolkit/query/mcp/model.py, cratedb_toolkit/query/mcp/pg_mcp.py, cratedb_toolkit/query/mcp/registry.py, cratedb_toolkit/query/mcp/util.py, doc/backlog/main.md, doc/query/index.md, doc/query/mcp/backlog.md, doc/query/mcp/index.md, doc/query/mcp/landscape.md, doc/query/mcp/notes.md, pyproject.toml, tests/query/test_mcp.py
Based on a few patches to `cratedb-examples` about exploring capabilities of existing MCP server implementations that can talk to CrateDB, this patch adds a few utilities for MCP servers and clients, which can be invoked from the CLI using the `ctk query mcp {list,inquire,launch}` subcommands.
The patch also includes corresponding documentation which shares insights about relevant MCP server capabilities in detail. It has been automatically generated from a [representation in code](https://github.com/crate/cratedb-toolkit/blob/mcp/cratedb_toolkit/query/mcp/registry.py), which can be used for other meta purposes as well.
https://cratedb-toolkit--392.org.readthedocs.build/query/mcp/index.html
https://cratedb-toolkit--392.org.readthedocs.build/query/mcp/landscape.html
- …
=> MCP: Subsystem providing a few server and client utilities and documentation about detailed API capabilities

cratedb_toolkit/query/mcp/registry.py, doc/query/mcp/landscape.md
MCP Alchemy is now available on PyPI.
https://pypi.org/project/mcp-alchemy/
- https://github.com/crate/cratedb-examples/pull/890
=> MCP: Update to `mcp-alchemy` GA from PyPI

pyproject.toml
Just a maintenance update.
Test failures on CI are unrelated to this patch, see https://github.com/crate/crate/issues/17691 instead.
- https://github.com/crate/sqlalchemy-cratedb/pull/215
- https://github.com/crate/cloud-api/pull/3089
- https://github.com/crate/grand-central/pull/208
=> TEMP: Update to "sqlalchemy-cratedb>=0.42.0.dev2"

pyproject.toml
When installing from GitHub using `git+http://...`, the caller needs to have the `git` program installed.
By using the `git-archive` method of `versioningit`, it can provide the software version also without.
=> Project: Improve configuration for `versioningit`, allow Zip-only setup

CHANGES.md, cratedb_toolkit/docs/settings.py
This tool extracts settings from CrateDB's documentation and outputs them
in either JSON or Markdown format, or the SQL statements to set the default value.
It parses the HTML structure of the documentation to identify settings, their
descriptions, default values, and whether they're runtime configurable.
Date: April 2025
Author: @WalBeh 
Source: https://gist.github.com/WalBeh/c863eb5cc35ee987d577851f38b64261
Thanks!
=> Docs API: Add CrateDB settings extractor

cratedb_toolkit/docs/cli.py, cratedb_toolkit/docs/settings.py, doc/docs-api.md, tests/docs/test_cli.py
Streamline and trim the rendering and output writing subsystem a bit.
When no output parameter is given, emit results to stdout.
Also enable rendering into YAML format.
```python
from cratedb_toolkit.docs.settings import SettingsExtractor
extractor = SettingsExtractor()
extractor.acquire().render(format).write(output)
```
=> Docs API: Use stdout by default. Add YAML output format.

cratedb_toolkit/docs/cli.py, cratedb_toolkit/docs/functions.py, cratedb_toolkit/docs/model.py, cratedb_toolkit/docs/settings.py, doc/docs-api.md, tests/docs/test_cli.py
Giving metadata a dedicated slot within the response, for both domains _settings_ vs. _functions_.
=> Docs API: Refactoring and refinement

cratedb_toolkit/query/mcp/inquiry.py, cratedb_toolkit/query/mcp/model.py, cratedb_toolkit/query/mcp/registry.py, doc/conf.py, doc/query/index.md, doc/query/mcp/backlog.md, doc/query/mcp/index.md, doc/query/mcp/landscape.md, doc/query/mcp/research.md, doc/query/mcp/sandbox.md, doc/query/mcp/server.md
Nothing special, just maintenance and documentation.
- [Update servers. Add example invocations using mcptools](https://github.com/crate/cratedb-toolkit/commit/3b02c624ac24365db77a631c3b1b9a339ba82342)
- [Improve documentation](https://github.com/crate/cratedb-toolkit/commit/1c8442fc828cd47eac29178ea40eecf1d49e9b16)
Preview: https://cratedb-toolkit--407.org.readthedocs.build/query/mcp/
=> MCP: Improve documentation

.github/workflows/release-oci.yml, CHANGES.md, cratedb_toolkit/cfr/jobstats.py, cratedb_toolkit/model.py, tests/test_model.py
The new `?sslmode=require` parameter with the `CRATEDB_SQLALCHEMY_URL` environment variable wasn't respected by the [CFR job statistics](https://cratedb-toolkit.readthedocs.io/cfr/jobstats.html) subsystem.
```shell
export CRATEDB_SQLALCHEMY_URL=crate://crate@localhost/?sslmode=require
ctk cfr jobstats collect
```
Respect `sslmode` URI parameter when converting SQLAlchemy connection URLs to `http(s)://`.
=> Connect: Respect `sslmode` URI parameter

cratedb_toolkit/adapter/pymongo/api.py, cratedb_toolkit/adapter/pymongo/collection.py, cratedb_toolkit/adapter/pymongo/cursor.py, cratedb_toolkit/adapter/rockset/server/api/document.py, cratedb_toolkit/adapter/rockset/server/api/query.py, cratedb_toolkit/adapter/rockset/server/dependencies.py, cratedb_toolkit/cfr/cli.py, cratedb_toolkit/cfr/info.py, cratedb_toolkit/cfr/systable.py, cratedb_toolkit/cluster/cli.py, cratedb_toolkit/cmd/tail/cli.py, cratedb_toolkit/cmd/tail/main.py, cratedb_toolkit/datasets/model.py, cratedb_toolkit/info/cli.py, cratedb_toolkit/info/http.py, cratedb_toolkit/info/model.py, cratedb_toolkit/io/dynamodb/copy.py, cratedb_toolkit/io/kinesis/relay.py, cratedb_toolkit/io/mongodb/cdc.py, cratedb_toolkit/io/mongodb/copy.py, cratedb_toolkit/model.py, cratedb_toolkit/testing/testcontainers/cratedb.py, cratedb_toolkit/util/__init__.py, examples/retention_edit.py, examples/retention_retire_cutoff.py, tests/datasets/conftest.py, tests/datasets/test_loading.py, tests/sqlalchemy/conftest.py, tests/util/database.py
=> Chore: Fix import woes

cratedb_toolkit/cfr/cli.py, cratedb_toolkit/cfr/jobstats.py, tests/cfr/test_jobstats.py
Enhance job statistics commands with optional reporting database support.
Adds a `--reportdb/-r` CLI option, that allows writing statement statistics to a separate database.
=> Enhance job statistics commands with optional reporting database support

CHANGES.md, cratedb_toolkit/meta/release.py, pyproject.toml, tests/meta/test_release.py
On day-to-day workflows, it is common to extract information from https://cratedb.com/releases.json, in order to pin-point specific release artefacts. The routines added here will make those operations more fluent, with less bashisms.
The blueprint was this routine in `scripts/croud-deploy-nightly.sh`. Thanks, @WalBeh.
```shell
nightly_url="$(curl -s https://cratedb.com/releases.json | jq -r '.nightly.downloads."tar.gz".url')"
nightly="$(echo $nightly_url | sed 's/^.*crate-//')"
nightly="nightly-${nightly%%.tar.gz}"
nightly="${nightly:0:-8}"
```
- CrateDB "nightly" support for GH-81
=> Meta: Add parser for `https://cratedb.com/releases.json` file

CHANGES.md, cratedb_toolkit/cfr/cli.py, cratedb_toolkit/cfr/jobstats.py, pyproject.toml, tests/cfr/test_jobstats.py
This allows to _anonymize_ the queries aggregated by `ctk cfr jobstats` by adding a `--anonymize` flag. Anonymization is built on the `https://queryanonymizer.com/` library. The strings replaced are saved to a json file (defaults to `decoder_dictionary.json`. This allows to reverse back to clear text, which might be useful for troubleshooting queries. 
```shell
ctk cfr jobstats collect --anonymize clusterABC.json
ctk cfr jobstats view --deanonymize clusterABC.json
```
=> Anonymize sql statements

CHANGES.md, pyproject.toml
=> Downgrade to sqlalchemy-cratedb 0.41, version 0.42 is not GA yet

CHANGES.md, pyproject.toml
71d29e7851bfdb apparently removed essential dependencies accidentally.
=> Added lost `pytest` dependencies to `cratedb-toolkit[testing]`

doc/query/mcp/research.md
- ~[ ] Link to issue this PR refers to (if applicable): Fixes #???~
=> Link to Google's MCP Toolbox for Databases

cratedb_toolkit/query/mcp/registry.py, doc/query/mcp/landscape.md, doc/query/mcp/sandbox.md
After releasing `cratedb-mcp`, let's adjust a few docs.
=> Documentation: `cratedb-mcp` has been released

CHANGES.md, cratedb_toolkit/settings/compare.py
Preview: `pip install --upgrade 'cratedb-toolkit[settings] @ git+https://github.com/crate/cratedb-toolkit.git@hlcianfagna/ctksettingscomparedefault0sdisabled'`
This addresses the issue of `stats.jobs_log_expiration` and `stats.operations_log_expiration` being flagged as not being default because the settings reads `0s` but the documentation says `0s (disabled)`
=> Fix comparison of 0s vs 0ms

CHANGES.md, cratedb_toolkit/cluster/core.py, cratedb_toolkit/io/kinesis/api.py, cratedb_toolkit/io/kinesis/model.py, cratedb_toolkit/io/kinesis/relay.py, doc/io/dms/standalone.md, examples/cdc/aws/dms-control-create-table.json, examples/cdc/aws/dms-data-load.json, examples/cdc/aws/dms-load-schema-direct-noddl.yaml, examples/cdc/aws/dms-load-schema-direct.yaml, examples/cdc/aws/dms-load-schema-universal-noddl.yaml, examples/cdc/aws/dms-load-schema-universal.yaml, examples/cdc/aws/dms-load-schema.yaml, pyproject.toml, tests/io/kinesis/test_cli.py, tests/io/kinesis/test_relay.py, tests/meta/test_release.py
Giving the DMS nozzle a way to accept settings and parameters, for example to relay primary key and column type map information.
```
uv tool install --upgrade 'cratedb-toolkit[kinesis] @ git+https://github.com/crate/cratedb-toolkit@dms-refinements'
```
https://cratedb-toolkit--469.org.readthedocs.build/io/dms/standalone.html#configuration
In the warren of code, a recipe appears,
Mapping keys and columns, allaying schema fears.
Through Kinesis it flows, to CrateDB’s delight,
With YAML and JSON, our tables set right.
Now rabbits can test, and users can see—
Transformation made simple, as easy as can be!
🐇✨
=> DMS: Accept a recipe file to receive settings and parameters

CHANGES.md, doc/backlog/main.md, doc/io/index.md, doc/io/ingestr/index.md, pyproject.toml
Another patch recently unlocked [ingestr](https://github.com/bruin-data/ingestr). This one brings in relevant documentation.
https://cratedb-toolkit--463.org.readthedocs.build/io/ingestr/
```shell
ctk load table \
"frankfurter://?base=EUR&table=latest" \
--cluster-url="crate://crate:na@localhost:4200/testdrive/exchange_latest"
ctk load table \
"frankfurter://?base=EUR&table=currencies" \
--cluster-url="crate://crate:na@localhost:4200/testdrive/exchange_currencies"
ctk load table \
"postgresql://pguser:secret11@postgresql.example.org:5432/postgres?table=information_schema.tables" \
--cluster-url="crate://crate:na@localhost:4200/testdrive/postgresql_tables"
```
- GH-445
=> I/O: Add documentation about `ingestr` adapter

pyproject.toml
=> Chore: Fix `mypy` type checking by downgrading `types-docutils`

pyproject.toml
```python
ValueError: numpy.dtype size changed, may indicate binary incompatibility.
```
On this error, it is advisable to downgrade to NumPy 1.x.
- https://github.com/daq-tools/skeem/issues/112
- https://github.com/crate/cratedb-toolkit/actions/runs/16666701610/job/47174409619?pr=493#step:7:46
=> Dependencies (PyMongo): Fix error with NumPy 2.x

.github/workflows/main.yml
Recent CI runs suddenly produced this error.
-- https://github.com/crate/cratedb-toolkit/actions/runs/16951193121/job/48044132939?pr=500#step:7:39
=> Chore: Remove Python 3.10 from compatibility support for Kinesis nozzle

CHANGES.md, cratedb_toolkit/cluster/core.py
Through a report by Võ Thiện, we found out the ingestr-based data nozzle was masking the existing native I/O adapters. This patch aims to fix it.
-- https://community.cratedb.com/t/using-ctk-ingestr-to-sync-mongodb-with-cratedb/2062
=> I/O: Tune down ingestr, it masked native I/O adapters

doc/io/ingestr/index.md
It is better handled by the built-in native I/O adapter.
- https://community.cratedb.com/t/using-ctk-ingestr-to-sync-mongodb-with-cratedb/2062
=> Ingestr: Remove "MongoDB to CrateDB" advice

CHANGES.md, cratedb_toolkit/io/influxdb.py, doc/io/influxdb/loader.md, pyproject.toml, tests/conftest.py, tests/io/influxdb/test_cli.py
This pulls in some updates to influxio. Thanks for the bug reports, @ZillKhan.
- GH-509
- https://github.com/daq-tools/influxio/issues/182
- https://github.com/daq-tools/influxio/issues/183
- https://github.com/daq-tools/influxio/releases/tag/v0.6.0
=> I/O: Update to `influxio-0.6.0`

CHANGES.md, cratedb_toolkit/settings/compare.py
... when `gateway.expected_nodes` and `gateway.expected_data_nodes` are not defined.
- GH-520
=> Settings: Stopped flagging `gateway.recover_after_time` as a difference

pyproject.toml
- [Chore: Mitigate Ruff warning](https://github.com/crate/cratedb-toolkit/commit/d7f8a865754b577f36b4c461409d0814f25e854c)
=> Maintenance 20251002
